### ISSUE TITLE
use github actions for ci

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/hclust#2]
```yaml
name: npm-publish

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Publish
      if: github.ref == 'refs/heads/master'
      uses: mikeal/merge-release@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
```
